module.exports={
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin',
    VENDOR_COLLECTION:'vendor',
    PRODUCT_COLLECTION:'products',
    CATEGORY_COLLECTION:'category',
    CART_COLLECTION:'cart',
    WISHLIST_COLLECTION:'wishlist',
    ORDER_COLLECTION:'orders',
    COUPON_COLLECTION:'coupon'
}